"""initial migration

Revision ID: 5b7d8df54fdf
Revises: 
Create Date: 2024-01-05 20:06:18.928290

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5b7d8df54fdf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('kkkkk', sa.String(length=80), nullable=False))
    op.create_unique_constraint(None, 'user', ['kkkkk'])
    op.drop_column('user', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', mysql.VARCHAR(collation='utf8mb3_bin', length=50), nullable=False))
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'kkkkk')
    # ### end Alembic commands ###
