"""empty message

Revision ID: 82f39eed0e9a
Revises: 5b7d8df54fdf
Create Date: 2024-01-05 20:32:11.608463

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '82f39eed0e9a'
down_revision = '5b7d8df54fdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.String(length=80), nullable=False))
    op.add_column('user', sa.Column('password', sa.String(length=80), nullable=False))
    op.drop_index('kkkkk', table_name='user')
    op.create_unique_constraint(None, 'user', ['email'])
    op.drop_column('user', 'kkkkk')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('kkkkk', mysql.VARCHAR(collation='utf8mb3_bin', length=80), nullable=False))
    op.drop_constraint(None, 'user', type_='unique')
    op.create_index('kkkkk', 'user', ['kkkkk'], unique=True)
    op.drop_column('user', 'password')
    op.drop_column('user', 'email')
    # ### end Alembic commands ###
